### ISSUE TITLE
_pyllamacpp.llama_context_params object has no attribute 'n_threads'

### ISSUE THREAD

**Issue by mkellerman** [nomic-ai/pyllamacpp#11]
Code executed:
```
from pyllamacpp.model import Model
model = Model(ggml_model='/Users/Shared/Models/7B/gpt4all-lora-quantized.ggml', n_ctx=512, n_threads=8)
```

full error:
```
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/me/.vscode/extensions/ms-python.python-2023.6.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/Users/me/.vscode/extensions/ms-python.python-2023.6.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/Users/me/.vscode/extensions/ms-python.python-2023.6.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/Users/me/.vscode/extensions/ms-python.python-2023.6.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/me/.vscode/extensions/ms-python.python-2023.6.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/me/.vscode/extensions/ms-python.python-2023.6.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/Users/me/Documents/GitHub/gpt4all-fastapi/pyllamacpp/pyllamacpp.py", line 4, in <module>
    model = Model(ggml_model='/Users/Shared/Models/7B/gpt4all-lora-quantized.ggml', n_ctx=512, n_threads=8)
  File "/Users/me/Documents/GitHub/gpt4all-fastapi/pyllamacpp/pyllamacpp/model.py", line 57, in __init__
    self._set_params(self.llama_params, llama_params)
  File "/Users/me/Documents/GitHub/gpt4all-fastapi/pyllamacpp/pyllamacpp/model.py", line 74, in _set_params
    setattr(params, param, kwargs[param])
AttributeError: '_pyllamacpp.llama_context_params' object has no attribute 'n_threads'
Exception ignored in: <function Model.__del__ at 0x103b11a60>
Traceback (most recent call last):
  File "/Users/me/Documents/GitHub/gpt4all-fastapi/pyllamacpp/pyllamacpp/model.py", line 136, in __del__
    pp.llama_free(self._ctx)
AttributeError: 'Model' object has no attribute '_ctx'
```

**Comment by MLTQ** [comment]
See: https://github.com/nomic-ai/pyllamacpp/issues/8#issuecomment-1495356796

**Comment by mkellerman** [comment]
Closing as it is a duplicate.
