### ISSUE TITLE
Cannot convert the model to new ggml format

### ISSUE THREAD

**Issue by kaanyalova** [nomic-ai/pyllamacpp#24]
```
ubuntu@instance-20230331-2018:~$ pyllamacpp-convert-gpt4all /home/ubuntu/models/gpt4all-lora-quantized.bin /home/ubuntu/models/tokenizer.model /home/ubuntu/models/gpt4all-lora-quantized.converted.bin 
Namespace(gpt4all_model='/home/ubuntu/models/gpt4all-lora-quantized.bin', tokenizer_model='/home/ubuntu/models/tokenizer.model', fout_path='/home/ubuntu/models/gpt4all-lora-quantized.converted.bin')
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/pyllamacpp-convert-gpt4all", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyllamacpp/scripts/convert_gpt4all.py", line 18, in main
    tokenizer = SentencePieceProcessor(args.tokenizer_model)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sentencepiece/__init__.py", line 447, in Init
    self.Load(model_file=model_file, model_proto=model_proto)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())] 
ubuntu@instance-20230331-2018:~$ 
```

**Comment by kaanyalova** [comment]
Nevermind, i did not download the tokenizer.model correctly
