### ISSUE TITLE
ggml model is not recognized

### ISSUE THREAD

**Issue by TenKenZero** [nomic-ai/pyllamacpp#25]
I converted the model using the Tokenizer.model from this source: https://huggingface.co/decapoda-research/llama-7b-hf/tree/main

But, the assignment of the model still gives me an error:

```
>>> llm = GPT4All(model_path=".\gpt4all-converted.bin")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydantic\main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic\main.py", line 1102, in pydantic.main.validate_model
  File "C:\Users\Lenin\AppData\Roaming\Python\Python310\site-packages\langchain\llms\gpt4all.py", line 132, in validate_environment
    ggml_model=values["model"],
KeyError: 'model'
```

**Comment by abdeladim-s** [comment]
Please read the [usage section ](https://github.com/nomic-ai/pyllamacpp#usage)
