### ISSUE TITLE
Error running the example code

### ISSUE THREAD

**Issue by itachiluan** [nomic-ai/pyllamacpp#9]
Hi,
I'm using a M1 cpu and installed the package using `pip install pyllamacpp` into a virtualenv.
When trying to run the code:
```python
from pyllamacpp.model import Model

def new_text_callback(text: str):
    print(text, end="")

model = Model(ggml_model='./models/gpt4all-model.bin', n_ctx=512, n_threads=8)
model.generate("Once upon a time, ", n_predict=55, new_text_callback=new_text_callback)
```

 I got the following error:

```
Traceback (most recent call last):
  File "/path/to/main.py", line 6, in <module>
    model = Model(ggml_model='./gpt4all-converted.bin', n_ctx=512, n_threads=8)
  File "/Users/user/env/lib/python3.10/site-packages/pyllamacpp/model.py", line 57, in __init__
    self._set_params(self.llama_params, llama_params)
  File "/Users/user/env/lib/python3.10/site-packages/pyllamacpp/model.py", line 74, in _set_params
    setattr(params, param, kwargs[param])
AttributeError: '_pyllamacpp.llama_context_params' object has no attribute 'n_threads'
Exception ignored in: <function Model.__del__ at 0x1029fa560>
Traceback (most recent call last):
  File "/Users/user/env/train-llama/lib/python3.10/site-packages/pyllamacpp/model.py", line 136, in __del__
    pp.llama_free(self._ctx)
AttributeError: 'Model' object has no attribute '_ctx'
```

Just wondering if I'm installing it wrong? Thanks!

**Comment by MLTQ** [comment]
See: https://github.com/nomic-ai/pyllamacpp/issues/8#issuecomment-1495356796

**Comment by mkellerman** [comment]
remove the `n_threads` parameter
